### ISSUE TITLE
Unnumbered marginal note missing in menu

### ISSUE THREAD

**Issue by MischaPanch** [appliedAI-Initiative/tm-transferlab#5]
The docu of the package states that in the Insert/Note menu there would be a new option: Unnumbered Note. This does not seem to be the case under windows (with the newest version of texmacs), so the option for unnumbered marginal notes is a bit hidden.

**Comment by mdbenito** [comment]
The problem is with the documentation, there should not be an entry "unnunmbered note", for consistency with the rest of the menus: In TeXmacs, unnumbered variants of environments are always obtained with the same method, either with the icon "IV" in the focus bar or with the shortcut Ctr+Shift+# (search for "structured variants" in TeXmacs' documentation). 

I think rephrasing the doc to say "there is a new unnumbered variant of marginal notes" or something like that would be better.
